name: gymverse_frontend
description: A Flutter app for Gym and Fitness tracking.

publish_to: 'none' # Prevents accidental publishing
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.9.5
  url_launcher: ^6.2.5
  tflite_flutter_helper: ^0.2.0
  google_fonts: ^6.1.0
  http: ^1.3.0
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  google_sign_in: ^5.2.4  # or the latest stable version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
